export * from './academicYear.schema';
export * from './class.schema';
export * from './division.schema';
export * from './subject.schema';
export * from './teacher.schema';
export * from './assignment.schema';
export * from './electiveGroup.schema';
export * from './timetable.schema';
export * from './slot.schema';
