// Errors
export {
  AppError,
  NotFoundError,
  ConflictError,
  ValidationError,
  ForbiddenError,
} from './errors';

// Helpers
export {
  success,
  paginated,
  created,
  accepted,
  noContent,
  errorResponse,
  parsePagination,
  type PaginationParams,
  parseBody,
  invokeLambda,
  findTeachersAtTime,
  isTeacherBusyAt,
  buildTeacherBusyRanges,
  isTeacherBusyInRanges,
  type TimeConflictResult,
  type BusyRange,
  identifyCrossDivElectiveGroups,
  buildElectiveGroupDivisionMap,
  buildElectiveGroupClassName,
  computeTeacherLoads,
  type TeacherLoadResult,
  loadPeriodSlots,
  loadDivisionPeriodSlots,
  type PeriodSlot,
  type PeriodSlotResult,
  checkDuplicateName,
  buildAuditContext,
  type AuditContext,
  writeAuditLog,
  computeChanges,
  type AuditLogEntry,
  hasPermission,
  requirePermission,
  getPermissionsForRole,
  PERMISSION_MATRIX,
  type Permission,
  type PermissionUserRole,
  TimetableStatusTag,
  STATUS_SEVERITY,
  recomputeTimetableStatus,
  recomputeMultipleTimetableStatuses,
  findAffectedTimetableIds,
  findTimetablesFlaggingTeachers,
  type TimetableStatusTagType,
  type TimetableStatusJson,
  annotateSlotViolations,
  type SlotViolation,
  assessAssignmentImpact,
  type AssignmentImpact,
  type ResolutionStep,
  type ResolutionStepType,
  type TeacherConflictDetails,
  type SlotRemovalDetails,
  type SlotFillDetails,
  type PwBalanceDetails,
  type WeightageAdjustmentDetails,
  sendEmail,
  EMAIL_TEMPLATES,
  type EmailParams,
  checkTierAllows,
  checkSubscriptionStatus,
  TIER_LIMITS,
  type SubscriptionTier,
  type TierLimits,
  type SubscriptionAction,
} from './helpers';

// Middleware
export {
  authMiddleware,
  resolveSchoolId,
  academicYearMiddleware,
  requestLogger,
  errorHandler,
  checkPermission,
  type RequestContext,
} from './middleware';

// Database
export { prisma, tenantScope, softDelete } from './db';

// Models — enums
export {
  SlotType,
  JobStatus,
  AcademicYearStatus,
  ConflictType,
  DayOfWeek,
  UserRole,
} from './models';

// Models — schemas & DTOs
export {
  createAcademicYearSchema,
  updateAcademicYearSchema,
  type CreateAcademicYearDto,
  type UpdateAcademicYearDto,
  createClassSchema,
  updateClassSchema,
  updateSortOrderSchema,
  type CreateClassDto,
  type UpdateClassDto,
  type UpdateSortOrderDto,
  createDivisionSchema,
  updateDivisionSchema,
  type CreateDivisionDto,
  type UpdateDivisionDto,
  createSubjectSchema,
  updateSubjectSchema,
  type CreateSubjectDto,
  type UpdateSubjectDto,
  createTeacherSchema,
  updateTeacherSchema,
  setTeacherSubjectsSchema,
  setTeacherAvailabilitySchema,
  type CreateTeacherDto,
  type UpdateTeacherDto,
  type SetTeacherSubjectsDto,
  type SetTeacherAvailabilityDto,
  createAssignmentSchema,
  updateAssignmentSchema,
  type CreateAssignmentDto,
  type UpdateAssignmentDto,
  getAssignmentImpactSchema,
  resolvePwBalanceSchema,
  resolveSlotRemovalSchema,
  resolveSlotFillSchema,
  type GetAssignmentImpactDto,
  type ResolvePwBalanceDto,
  type ResolveSlotRemovalDto,
  type ResolveSlotFillDto,
  createElectiveGroupSchema,
  updateElectiveGroupSchema,
  addElectiveSubjectSchema,
  updateElectiveSubjectSchema,
  bulkSaveElectiveGroupSchema,
  type CreateElectiveGroupDto,
  type UpdateElectiveGroupDto,
  type AddElectiveSubjectDto,
  type UpdateElectiveSubjectDto,
  type BulkSaveElectiveGroupDto,
  schedulingPreferencesSchema,
  triggerGenerationSchema,
  overrideSlotSchema,
  swapSlotsSchema,
  autoResolveSchema,
  createEmptySlotSchema,
  swapElectiveSlotsSchema,
  previewElectiveSwapSchema,
  previewTeacherSwapSchema,
  type TriggerGenerationDto,
  type OverrideSlotDto,
  type SwapSlotsDto,
  type AutoResolveDto,
  type CreateEmptySlotDto,
  type SwapElectiveSlotsDto,
  type PreviewElectiveSwapDto,
  type PreviewTeacherSwapDto,
  createPeriodStructureSchema,
  updatePeriodStructureSchema,
  assignPeriodStructureSchema,
  setWorkingDaysSchema,
  addSlotSchema,
  updateSlotSchema,
  reorderSlotsSchema,
  type CreatePeriodStructureDto,
  type UpdatePeriodStructureDto,
  type AssignPeriodStructureDto,
  type SetWorkingDaysDto,
  type SlotEntry,
  type AddSlotDto,
  type UpdateSlotDto,
  type ReorderSlotsDto,
} from './models';
