// Errors
export {
  AppError,
  NotFoundError,
  ConflictError,
  ValidationError,
  ForbiddenError,
} from './errors';

// Helpers
export {
  success,
  paginated,
  created,
  accepted,
  noContent,
  errorResponse,
  parsePagination,
  type PaginationParams,
  parseBody,
  invokeLambda,
  flagAffectedTimetables,
  flagTimetables,
  findTeachersAtTime,
  isTeacherBusyAt,
  buildTeacherBusyRanges,
  isTeacherBusyInRanges,
  type TimeConflictResult,
  type BusyRange,
  identifyCrossDivElectiveGroups,
  buildElectiveGroupDivisionMap,
  buildElectiveGroupClassName,
  computeTeacherLoads,
  type TeacherLoadResult,
  loadPeriodSlots,
  loadDivisionPeriodSlots,
  type PeriodSlot,
  type PeriodSlotResult,
  checkDuplicateName,
  buildAuditContext,
  type AuditContext,
  writeAuditLog,
  computeChanges,
  type AuditLogEntry,
  hasPermission,
  requirePermission,
  getPermissionsForRole,
  PERMISSION_MATRIX,
  type Permission,
  type PermissionUserRole,
} from './helpers';

// Middleware
export {
  authMiddleware,
  resolveSchoolId,
  academicYearMiddleware,
  requestLogger,
  errorHandler,
  checkPermission,
  type RequestContext,
} from './middleware';

// Database
export { prisma, tenantScope, softDelete } from './db';

// Models — enums
export {
  SlotType,
  JobStatus,
  TimetableStatus,
  AcademicYearStatus,
  ConflictType,
  DayOfWeek,
  UserRole,
} from './models';

// Models — schemas & DTOs
export {
  createAcademicYearSchema,
  updateAcademicYearSchema,
  type CreateAcademicYearDto,
  type UpdateAcademicYearDto,
  createClassSchema,
  updateClassSchema,
  updateSortOrderSchema,
  type CreateClassDto,
  type UpdateClassDto,
  type UpdateSortOrderDto,
  createDivisionSchema,
  updateDivisionSchema,
  type CreateDivisionDto,
  type UpdateDivisionDto,
  createSubjectSchema,
  updateSubjectSchema,
  type CreateSubjectDto,
  type UpdateSubjectDto,
  createTeacherSchema,
  updateTeacherSchema,
  setTeacherSubjectsSchema,
  setTeacherAvailabilitySchema,
  type CreateTeacherDto,
  type UpdateTeacherDto,
  type SetTeacherSubjectsDto,
  type SetTeacherAvailabilityDto,
  createAssignmentSchema,
  updateAssignmentSchema,
  type CreateAssignmentDto,
  type UpdateAssignmentDto,
  createElectiveGroupSchema,
  updateElectiveGroupSchema,
  addElectiveSubjectSchema,
  updateElectiveSubjectSchema,
  bulkSaveElectiveGroupSchema,
  type CreateElectiveGroupDto,
  type UpdateElectiveGroupDto,
  type AddElectiveSubjectDto,
  type UpdateElectiveSubjectDto,
  type BulkSaveElectiveGroupDto,
  schedulingPreferencesSchema,
  triggerGenerationSchema,
  overrideSlotSchema,
  swapSlotsSchema,
  autoResolveSchema,
  createEmptySlotSchema,
  swapElectiveSlotsSchema,
  previewElectiveSwapSchema,
  type TriggerGenerationDto,
  type OverrideSlotDto,
  type SwapSlotsDto,
  type AutoResolveDto,
  type CreateEmptySlotDto,
  type SwapElectiveSlotsDto,
  type PreviewElectiveSwapDto,
  createPeriodStructureSchema,
  updatePeriodStructureSchema,
  assignPeriodStructureSchema,
  setWorkingDaysSchema,
  addSlotSchema,
  updateSlotSchema,
  reorderSlotsSchema,
  type CreatePeriodStructureDto,
  type UpdatePeriodStructureDto,
  type AssignPeriodStructureDto,
  type SetWorkingDaysDto,
  type SlotEntry,
  type AddSlotDto,
  type UpdateSlotDto,
  type ReorderSlotsDto,
} from './models';
