export enum SlotType {
  PERIOD = 'PERIOD',
  INTERVAL = 'INTERVAL',
  LUNCH_BREAK = 'LUNCH_BREAK',
}

export enum JobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum TimetableStatus {
  GENERATED = 'GENERATED',
  OUTDATED = 'OUTDATED',
}

export enum AcademicYearStatus {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum ConflictType {
  TEACHER_CHANGED = 'TEACHER_CHANGED',
  TEACHER_DELETED = 'TEACHER_DELETED',
  SUBJECT_CHANGED = 'SUBJECT_CHANGED',
  SUBJECT_DELETED = 'SUBJECT_DELETED',
  ASSIGNMENT_CHANGED = 'ASSIGNMENT_CHANGED',
  SLOT_CHANGED = 'SLOT_CHANGED',
  STRUCTURE_CHANGED = 'STRUCTURE_CHANGED',
  AVAILABILITY_CHANGED = 'AVAILABILITY_CHANGED',
  ELECTIVE_GROUP_CHANGED = 'ELECTIVE_GROUP_CHANGED',
}

export enum DayOfWeek {
  MONDAY = 0,
  TUESDAY = 1,
  WEDNESDAY = 2,
  THURSDAY = 3,
  FRIDAY = 4,
  SATURDAY = 5,
  SUNDAY = 6,
}
